export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-primary": "#ffffff",
          "secondary": "#745b00",
          "tertiary-container": "#1a3455",
          "on-error": "#ffffff",
          "on-secondary-container": "#6e5700",
          "primary-container": "#003366",
          "on-background": "#191c1d",
          "tertiary": "#001f3e",
          "surface": "#f8f9fa",
          "inverse-surface": "#2e3132",
          "background": "#f8f9fa",
          "surface-dim": "#d9dadb",
          "secondary-fixed-dim": "#f1c100",
          "on-secondary": "#ffffff",
          "on-tertiary-fixed": "#001c3a",
          "surface-container-low": "#f3f4f5",
          "error-container": "#ffdad6",
          "surface-container-highest": "#e1e3e4",
          "outline-variant": "#c3c6d1",
          "on-primary-fixed-variant": "#1f477b",
          "inverse-primary": "#a7c8ff",
          "on-tertiary-fixed-variant": "#2f486a",
          "primary-fixed-dim": "#a7c8ff",
          "primary-fixed": "#d5e3ff",
          "outline": "#737780",
          "surface-container": "#edeeef",
          "primary": "#001e40",
          "surface-bright": "#f8f9fa",
          "secondary-container": "#fecb00",
          "on-surface": "#191c1d",
          "inverse-on-surface": "#f0f1f2",
          "error": "#ba1a1a",
          "tertiary-fixed-dim": "#afc8f0",
          "surface-tint": "#3a5f94",
          "on-secondary-fixed-variant": "#584400",
          "on-error-container": "#93000a",
          "on-secondary-fixed": "#241a00",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-container": "#849dc3",
          "on-primary-container": "#799dd6",
          "on-primary-fixed": "#001b3c",
          "surface-container-high": "#e7e8e9",
          "on-tertiary": "#ffffff",
          "on-surface-variant": "#43474f",
          "secondary-fixed": "#ffe08b",
          "tertiary-fixed": "#d4e3ff",
          "surface-variant": "#e1e3e4"
        },
        fontFamily: {
          "headline": ["Manrope"],
          "body": ["Inter", "Manrope"],
          "label": ["Inter"]
        },
        borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
      },
    },
    plugins: [],
  }
